#!/bin/bash

# etre en root

var="/var/log/update_script.log"

touch $var

date >> $var

apt-get update >> $var

apt-get upgrade >> $var

#commande pour tache plannifiee :

#crontab -e
#0 4 * * 0 /home/debianvm/Init/Scripting/02
